### ISSUE TITLE
Improved Streaming Support

### ISSUE THREAD

**Issue by oubiwann** [clojusc/ring-xml#4]
Features/Investigations:
 * [ ] Investigate use of streaming in Ring - #6
 * [ ] Examine streaming XML examples in the wild - #7
 * [ ] Update `ring-xml` streaming - #8

Part of release #3
