### ISSUE TITLE
Improved CI/CD

### ISSUE THREAD

**Issue by oubiwann** [clojusc/ring-xml#5]
Tasks/Investigations:
 * [x] Find out the lowest supported Clojure for all combined deps - #20
 * [x] Create build matrix for all possible Clojure and Java versions - #21
 * [x] Ensure all combinations build on Travis CI - #22
 * [x] Ensure all combinations pass the tests on Travis CI - #23

Part of release #3
