### ISSUE TITLE
Investigate use of streaming in Ring

### ISSUE THREAD

**Issue by oubiwann** [clojusc/ring-xml#6]
Tasks:
 * [ ] Examine `StreamableResponseBody` in ring - #9
 * [ ] Examine `ring-jetty-adapter/test/ring/adapter/test/jetty.clj` - #10
 * [ ] Examine `ring-core/test/ring/util/test/response.clj` - #11
 * [ ] Based upon ring code, make tentative recommendation - #12

Part of epic #4
