### ISSUE TITLE
Examine streaming XML examples in the wild

### ISSUE THREAD

**Issue by oubiwann** [clojusc/ring-xml#7]
Tasks:
 * [ ] Carefully read [Streaming responses using ring](https://nelsonmorris.net/2015/04/22/streaming-responses-using-ring.html) - #13
 * [ ] Carefully read [mail list thread](https://groups.google.com/forum/#!topic/clojure/2gUUbhG1SlQ) - #14
 * [ ] Based upon readings, make tentative recommendation - #15

Part of epic #4
