### ISSUE TITLE
Update ring-xml streaming

### ISSUE THREAD

**Issue by oubiwann** [clojusc/ring-xml#8]
Tasks:
 * [ ] Implement prototypical solution based upon recommendations (#12, #15) during discovery phase - #16
 * [ ] Ensure solution works with jetty server - #17
 * [ ] Ensure solution works with http-kit server - #18
 * [ ] Add unit tests - #19

Part of epic #4
